image: mephux/docker-golang
git:
  path: github.com/mephux/rmslack
  branches:
    - master
script:
  - go get github.com/mitchellh/gox
  - make
notify:
  email:
    recipients:
      - dustin.webber@gmail.com
publish:
  github:
    branch: master
    script:
      - make release
    artifacts:
      - release
    tag: v$(cat .Version)
    token: $$github_token
    user: mephux
    repo: rmslack
